version:                           "3.5"

services:
#  web:
#    build:                        .
#    container_name:               rls-web
#    ports:
#      - "5000:5000"

  redis:
    container_name:                shop-redis
    image:                         "redis:alpine"
    ports:
      - 6379:6379

  mysql:
    image:                         mariadb
    restart:                       always
    container_name:                shop-mysql
    volumes:
     - ./tmp_data/storage/mysql:/var/lib/mysql
     - ./tmp_data:/data
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    #   MYSQL_ROOT_PASSWORD:        ${DB_ROOT_PASS:-blaze}
       MYSQL_DATABASE:             ${DB_NAME:-MyDB}
    #   MYSQL_USER:                ${DB_USR:-root}
    #  MYSQL_PASSWORD:             ${DB_PAS:-pass}
    ports:
      - 3306:3306

  mongodb:
      image:                       mongo
      container_name:              shop-mongodb
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
        - MONGO_INITDB_DATABASE='blazedb'
        #- MONGO_INITDB_ROOT_USERNAME=guest
        #- MONGO_INITDB_ROOT_PASSWORD=guest

      volumes:
        - ./tmp_data/storage/mongodb:/data/db
      ports:
          - 27017:27017
      command:                     mongod --logpath=/dev/null # --quiet
